<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0;netstandard2.0</TargetFrameworks>
		<WarningLevel>3</WarningLevel>
		<NoWarn>1573,1591,IDE0090,IDE0130</NoWarn>
		<DocumentationFile>bin/$(Configuration)/$(TargetFramework)/VIEApps.Services.Abstractions.xml</DocumentationFile>
		<RootNamespace>net.vieapps.Services</RootNamespace>
		<AssemblyName>VIEApps.Services.Abstractions</AssemblyName>
		<AssemblyTitle>VIEApps NGX Service Abstractions</AssemblyTitle>
		<AssemblyVersion>10.9.2508.2</AssemblyVersion>
		<FileVersion>10.9.2508.2</FileVersion>
		<Version>10.9.2508.2</Version>
		<InformationalVersion>10.9.$([System.DateTime]::Now.Year).$([System.DateTime]::Now.Month).$([System.DateTime]::Now.Day)@$(TargetFramework)#moving.forward</InformationalVersion>
		<Title>VIEApps NGX Service Abstractions</Title>
		<Description>The abstractions for all microservices in the VIEApps NGX</Description>
		<Authors>VIEApps.net</Authors>
		<Company>VIEApps.net</Company>
		<Product>VIEApps NGX</Product>
		<Copyright>© $([System.DateTime]::Now.Year) VIEApps.net</Copyright>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageId>VIEApps.Services.Abstractions</PackageId>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>Icon.png</PackageIcon>
		<PackageOutputPath>../../Components</PackageOutputPath>
		<PackageTags>services;microservices;vieapps;vieapps.components;vieapps.services;vieapps.microservices</PackageTags>
		<PackageReleaseNotes>Session extensions</PackageReleaseNotes>
		<PackageProjectUrl>https://vieapps.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/vieapps/Services.Abstractions</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Remove=".DS_Store" />
		<None Remove=".gitattributes" />
		<None Remove=".gitignore" />
		<None Visible="false" Include="README.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="LICENSE.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="Icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Reactive" Version="6.0.1" />
		<PackageReference Include="VIEApps.Components.Caching" Version="10.9.2508.2" />
		<PackageReference Include="VIEApps.Components.Security" Version="10.9.2508.2" />
		<PackageReference Include="WampSharp.Default.Client" Version="23.8.1" />
	</ItemGroup>

</Project>